name: k3s_infra
runtime:
  name: python
  options:
    toolchain: pip
    virtualenv: venv
description: A minimal AWS Python Pulumi program
config:
  pulumi:tags:
    value:
      pulumi:template: aws-python
